services:
  micro-notify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro-notify
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - whatsapp-auth:/app/data/baileys-auth
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: notify-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  whatsapp-auth:
  redis-data:
